sudo: required

servis: docker

before_install:
  - docker-compose up --build -d
addons:
  chrome: stable
 
script:
  - docker-compose exec --env 'RAILS_ENV'=test web rails db:create
  - docker-compose exec --env 'RAILS_ENV'=test web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV'=test web bundle rails webpacker:compile 
  - docker-compose exec --env 'RAILS_ENV'=test web bundle exec rspec 
 