sudo: required

servis: docker

before_install:
  - docker-compose up --build -d
  - brew cask install google-chrome
 
script:
  - docker-compose exec --env 'RAILS_ENV'=test web rails db:create
  - docker-compose exec --env 'RAILS_ENV'=test web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV'=test web bundle exec rspec 
 