version: '3'
volumes:
  mysql-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/breakin-community'
    environment:
      - 'DATABASE_PASSWORD=password'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.6
    volumes:
      - 'mysql-data:/var/lib/mysql'
    environment:
      - 'MYSQL_DATABASE=breakin-community'
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=password'
      - 'MYSQL_RANDOM_ROOT_PASSWORD=password'
    ports:
      - "4306:3306"