version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306" #sequelproでDBを可視化するため

  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/breakin-community
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    env_file: my_env_file.env
    environment: #travisCIでchromeを使うため
    - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"

volumes:
  mysql-data:
  bundle: